#!/bin/sh
# OpsWeave Single-Container Entrypoint
# Auto-generates secrets and initializes the database on first start.

set -e

ENV_FILE="/data/.env"
DB_FILE="/data/opsweave.db"

# Generate a random hex secret (32 bytes = 64 hex chars)
generate_secret() {
  head -c 32 /dev/urandom | od -A n -t x1 | tr -d ' \n'
}

# On first start, generate secrets and persist them
if [ ! -f "$ENV_FILE" ]; then
  echo "==> First start: generating secrets..."
  cat > "$ENV_FILE" <<EOF
# Auto-generated by OpsWeave on first start.
# Edit this file to customize settings, then restart the container.
JWT_SECRET=$(generate_secret)
SESSION_SECRET=$(generate_secret)
DEFAULT_LANGUAGE=de
EOF
  echo "==> Secrets saved to $ENV_FILE"
fi

# Export all variables from the persisted env file
set -a
. "$ENV_FILE"
set +a

# On first start (no database file), create tables and seed demo data
if [ ! -f "$DB_FILE" ]; then
  echo "==> Initializing database (creating tables)..."
  node packages/backend/dist/db/setup.js
  echo "==> Seeding demo data..."
  node packages/backend/dist/db/seed/index.js
  echo "==> Database ready."
fi

echo "==> Starting OpsWeave..."
exec "$@"
